version: '3'
services:
  proxy:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  web:
    image: nginx:latest
    expose:
      - "8080"
    volumes:
      - ./source/reid:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
        context: .
        dockerfile: php/Dockerfile
    volumes:
      - ./source/reid:/source